### ISSUE TITLE
Why T(n) = T(n/5) + (lg n)^2 is in case 2 ?

### ISSUE THREAD

**Issue by yoyolicoris** [NCTU-CSE-Introduction-to-Algorithms/Quiz-discuss#2]
乳題
from "Quiz 1 Solution---Introduction to Algorithms, Spring 2015" 
1- c .

a = 1 , b = 5 , n^logb a = 1 < f(n) = (lg n)^2 , so it should be in case 3 right ?

**Comment by dd-n-kk** [comment]
1 is not polynomially smaller than (lgn)^2 so it can't be case 3
there seems to be a more general form of master theorem, where case 2 is actually:
if f(n) = theta( n^logb(a) \* (lgn)^k ), where k>=0
then T(n) = theta( n^logb(a) \* (lgn)^(k+1) )
so in 1-c T(n) = theta( n^0 \* (lgn)^(2+1) ) = theta( (lgn)^3 )

**Comment by yoyolicoris** [comment]
"1 is not polynomially smaller than (lgn)^2 so it can't be case 3"
WHY???因為兩個都不到一次所以不成立ㄇ
圖都畫出來這樣耶
http://imgur.com/rwBTssZ

**Comment by dd-n-kk** [comment]
when we say f is polynomially smaller than g, we mean:
there is some constant real number c>0 such that
f = O(g \* n^(-c))
(or g = omega(f \* n^c))

we can show by l'Hopital's rule that
for any real p and any c>0, (lgn)^p \* n^(-c) = (lgn)^p / n^c approaches 0 when n is large enough
0 < 1, so 1 can never be O( (lgn)^2 \* n^(-c) )

graphs are not very useful here
the graph of 0.00001n and that of 1 will look very similar, but 1 = o(0.00001n)
the graph of 0.00001n and that of 999999n will look very different, but 0.00001n = theta(999999n)
